# --- 1. ConfigMap (للإعدادات العامة) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-office-config
data:
  FLASK_ENV: "production"
  APP_NAME: "Smart Office Controller v1"

---
# --- 2. Secret (للبيانات الحساسة) ---
apiVersion: v1
kind: Secret
metadata:
  name: smart-office-secret
type: Opaque
stringData:
  # لاحظ: سنستخدم اسم الخدمة 'mongodb-service' الذي سننشئه لاحقاً
  mongo-uri: "mongodb://mongodb-service:27017/smart_office"