# --- 1. ConfigMap (General Settings) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-office-config
data:
  FLASK_ENV: "production"
  APP_NAME: "Smart Office Controller v1"

---
# --- 2. Secret (Sensitive Data) ---
apiVersion: v1
kind: Secret
metadata:
  name: smart-office-secret
type: Opaque
stringData:
  # Note: We use the service name 'mongodb-service' which will be created later
  mongo-uri: "mongodb://mongodb-service:27017/smart_office"